name: mixer
description: mixer.com api library for dart
version: 0.1.0
homepage: https://github.com/aoisensi/mixer.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
